export interface ErrorLog {
    id: number,
    userId?: number,
    userName?: string,
    mobile?: string,
    statusCode?: number,
    errorMessage?: any,
    trace?: any,
    header?: any,
    request?: any,
    requestParams?: any,
    source?: string,
    module?: string, 
    url?: string,
    referer?: string,
    requestMethod?: string,
    userAgent?: string,
    threadName?: string,
    requestId?: string,
    appVersion?: string,
    startTime?: Date,
    endTime?: Date
}